[profile.default]
solc_version = '0.8.30'
src = 'contracts'
out = 'out'
cache_path = 'cache'
libs = [
    'node_modules'
]
fs_permissions = [{ access = "read-write", path = "./"}]

remappings = [
     'forge-std/=node_modules/forge-std/src',
     '@openzeppelin/=node_modules/@openzeppelin',
     '@solmate/=node_modules/solmate/src',
     '@boring-vault/=node_modules/boring-vault',
     'src/=node_modules/boring-vault/src',
     '@predicate/=node_modules/@predicate/contracts',
     '@pendle/=node_modules/@pendle',
     'createx/=node_modules/createx/src',
     'solidity-bytes-utils/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/solidity-bytes-utils/',
     '@layerzerolabs/=node_modules/@layerzerolabs/',
     '@uniswap/permit2/=node_modules/@uniswap/permit2/src/',
]

via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC}"
base = "${BASE_RPC}"
ethereum = "${ETHEREUM_RPC_URL}"
hyperevm = "${HYPEREVM_RPC}"
berachain = "${BERACHAIN_RPC}"
bsc = "${BSC_RPC}"